# in order to parametrize the 
testMode: assertion
# The deployer and sender must be the same for this example.
# The deployer is the 'attacker'
deployer: '0x30000'
# Sender must be the same as it is also a attacker. 
sender: ['0x30000']
# Allow for multi-abi use
multi-abi: true
